"""financial_report

Revision ID: 7c573047f275
Revises: 
Create Date: 2026-04-16 15:23:14.118618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c573047f275'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.String(length=10), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=True),
    sa.Column('taxpayer_id', sa.String(length=30), nullable=True),
    sa.Column('taxpayer_name', sa.String(length=100), nullable=True),
    sa.Column('period_start', sa.String(length=20), nullable=True),
    sa.Column('period_end', sa.String(length=20), nullable=True),
    sa.Column('balance_sheet', sa.Text(), nullable=True),
    sa.Column('income_stmt', sa.Text(), nullable=True),
    sa.Column('cashflow_stmt', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('financial_report')
    # ### end Alembic commands ###
