"""initial

Revision ID: bc41361a8528
Revises: 
Create Date: 2026-04-16 10:23:00.911866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc41361a8528'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quarterly_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('income_total', sa.Float(), nullable=True),
    sa.Column('income_tax_free', sa.Float(), nullable=True),
    sa.Column('income_taxable', sa.Float(), nullable=True),
    sa.Column('vat_rate', sa.Float(), nullable=True),
    sa.Column('vat_amount', sa.Float(), nullable=True),
    sa.Column('vat_exempt', sa.Boolean(), nullable=True),
    sa.Column('urban_maintenance_tax', sa.Float(), nullable=True),
    sa.Column('education_surcharge', sa.Float(), nullable=True),
    sa.Column('local_education_surcharge', sa.Float(), nullable=True),
    sa.Column('total_profit', sa.Float(), nullable=True),
    sa.Column('taxable_income', sa.Float(), nullable=True),
    sa.Column('income_tax_rate', sa.Float(), nullable=True),
    sa.Column('income_tax_amount', sa.Float(), nullable=True),
    sa.Column('income_tax_prepaid', sa.Float(), nullable=True),
    sa.Column('income_tax_due', sa.Float(), nullable=True),
    sa.Column('stamp_tax', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('invoice_no', sa.String(length=50), nullable=True),
    sa.Column('buyer', sa.String(length=200), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('tax_amount', sa.Float(), nullable=True),
    sa.Column('invoice_type', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['quarterly_report.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice')
    op.drop_table('quarterly_report')
    # ### end Alembic commands ###
